name: Generate and Deploy JavaDoc

on:
  push:
    branches: [ 'main' ]

jobs:
  javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Generate JavaDoc
        run: ./gradlew aggregateJavadocs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build/docs/javadoc